const {
  map,
  range
} = require('ramda');
const { generateName } = require('basket-simulation-utils');
const { generatePlayer } = require('basket-simulation-player');

// clubName :: a -> string
function clubName() {
  // Names retrieved from http://listofrandomnames.com/
  // Remove duplicates via https://www.textfixer.com/tools/remove-duplicate-lines.php
  const adjectives = [
    'Royal',
    'Haunting',
    'Fearless',
    'Angry',
    'Bright',
    'Tough',
    'Skeleton',
    'Valiant',
    'Determined',
    'Steel',
    'Storm',
    'Regal',
    'Majestic',
    'Proud',
    'Naughty',
    'Mysterious',
    'Brutal',
    'True',
    'Careless',
    'Enchanted',
    'Bold',
    'Mean',
    'Terrific',
    'Mad',
    'Gruesome',
    'Stark',
    'United',
    'Grand',
    'Hard',
    'Loyal',
    'Grim',
    'Fiery',
    'Thunder',
    'Silent',
    'Silver',
    'Happy',
    'Monstrous',
    'Wild',
    'Giant',
    'Lucky',
    'Young',
    'Strong',
    'Wicked',
    'Classic',
    'Creative',
    'Bitter',
    'Calm',
    'Clever',
    'Free',
    'Blue',
    'Dapper',
    'Fabulous',
    'White',
    'Marvelous',
    'Crazy',
    'Colossal',
    'Spectacular',
    'Fast',
    'Earnest',
    'Hidden',
    'Grave',
    'Potent',
    'Big',
    'Brave',
    'Powerful'
  ];
  const animals = [
    'Parrots',
    'Bulldogs',
    'Zebras',
    'Birds',
    'Wizards',
    'Ants',
    'Gusts',
    'Crickets',
    'Saints',
    'Donkeys',
    'Wings',
    'Raccoons',
    'Bats',
    'Nationals',
    'Bullets',
    'Warriors',
    'Squirrels',
    'Bees',
    'Braves',
    'Sabretooths',
    'Ninjas',
    'Riddles',
    'Hammers',
    'Crocodiles',
    'Sharks',
    'Rhinos',
    'Dinos',
    'Novas',
    'Androids',
    'Snowstorms',
    'Turtles',
    'Ocelots',
    'Mallards',
    'Mythics',
    'Goats',
    'Ferrets',
    'Zombies',
    'Doves',
    'Legends',
    'Kangaroos',
    'Robins',
    'Sirens',
    'Dolphins',
    'Elephants',
    'Boulders',
    'Pigeons',
    'Coyotes',
    'Deer',
    'Mavericks',
    'Alligators',
    'Gorillas',
    'Hedgehogs',
    'Stags',
    'Bottle',
    'Rockets',
    'Striders',
    'Koalas',
    'Blazers',
    'Monarchs',
    'Sliders',
    'Vikings',
    'Hounds',
    'Creatures',
    'Anacondas',
    'Grizzlies',
    'Mammoths',
    'Foxes',
    'Falcons',
    'Jaguars',
    'Hornets',
    'Raiders',
    'Toucans',
    'Beluga',
    'Whales',
    'Pythons',
    'Alphas',
    'Leopards',
    'Wreckers',
    'Blazes',
    'Howlers',
    'Comets',
    'Rovers',
    'Cougars',
    'Hawks',
    'Monkeys',
    'Gnomes',
    'Turkeys'
  ];

  return generateName([adjectives, animals]);
}

// generateClub :: a -> object
function generateClub() {
  return {
    name: clubName(),
    proTeam: initTeam(12),
    youthTeam: initTeam(10)
  };
}

// initTeam :: number -> [object]
function initTeam(nbPlayers) {
  return map(generatePlayer, range(0, nbPlayers));
}

exports.generateClub = generateClub;
